Allow select PHP version; use some sane defaults for Ubuntu LTS
Avature/dh-make-php pull request #18
Opened 2018-02-26 16:24 UTC by juan-leon

2018-02-26 18:48 UTC, jvrsantacruz requested changes

2018-02-26 18:48 UTC, jvrsantacruz commented on dh-make-pecl
> +}
This is Ubuntu-specific code, while the tool is not.

Might be better to check the default installed version of php?

```bash
function get_php_version {
    php --version | head -1 | sed 's/PHP \([0-9]\.[0-9]\).*/\1/g'
}
```

2018-02-27 07:48 UTC, juan-leon commented
Implemented suggested changes

2018-02-27 15:49 UTC, jvrsantacruz approved these changes

2018-02-27 15:49 UTC, merged